// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzIe2LV0JFfXOi048MvkuC_9NxXLHv4v8',
    appId: '1:515047456154:web:fdde888e7c872439e00e23',
    messagingSenderId: '515047456154',
    projectId: 'tabloy-iman',
    authDomain: 'tabloy-iman.firebaseapp.com',
    storageBucket: 'tabloy-iman.firebasestorage.app',
    measurementId: 'G-0SKQ945Q6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5MHbA_JAEnMXWDxzN9apJ_wi5j6QtGgQ',
    appId: '1:515047456154:android:8e79254091b9bface00e23',
    messagingSenderId: '515047456154',
    projectId: 'tabloy-iman',
    storageBucket: 'tabloy-iman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD5ouqJUe4Aq4CwQR43oQm2mO3IO-9ZbM',
    appId: '1:515047456154:ios:3161da2506a863dce00e23',
    messagingSenderId: '515047456154',
    projectId: 'tabloy-iman',
    storageBucket: 'tabloy-iman.firebasestorage.app',
    iosBundleId: 'com.example.tabloyIman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD5ouqJUe4Aq4CwQR43oQm2mO3IO-9ZbM',
    appId: '1:515047456154:ios:3161da2506a863dce00e23',
    messagingSenderId: '515047456154',
    projectId: 'tabloy-iman',
    storageBucket: 'tabloy-iman.firebasestorage.app',
    iosBundleId: 'com.example.tabloyIman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzIe2LV0JFfXOi048MvkuC_9NxXLHv4v8',
    appId: '1:515047456154:web:064a16a31056cffae00e23',
    messagingSenderId: '515047456154',
    projectId: 'tabloy-iman',
    authDomain: 'tabloy-iman.firebaseapp.com',
    storageBucket: 'tabloy-iman.firebasestorage.app',
    measurementId: 'G-TETQN1WCB3',
  );
}
